#!/usr/bin/env python

import os
import shutil


# MODEL_ID = "stabilityai/stable-diffusion-2-1"
MODEL_CACHE = "diffusers-cache"
# SAFETY_MODEL_ID = "CompVis/stable-diffusion-safety-checker"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

import torch
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-scribble", torch_dtype=torch.float16, cache_dir = MODEL_CACHE
)

# to make sure that it actually works...
StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    cache_dir=MODEL_CACHE,
)

# our goal is to get this to work:
StableDiffusionControlNetPipeline.from_pretrained(
    "SG161222/Realistic_Vision_V1.3",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    cache_dir=MODEL_CACHE,
)